PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE COLLATE NOCASE,
 phone TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', role TEXT NOT NULL CHECK(role IN ('ADMIN','PICKER')),
 password_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), token_hash TEXT NOT NULL UNIQUE,
 expires_at TEXT NOT NULL, csrf_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS farms (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL, contact_person TEXT NOT NULL, phone TEXT NOT NULL, address TEXT NOT NULL,
 navigation_link TEXT, notes TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1))
);
CREATE TABLE IF NOT EXISTS seasons (
 id INTEGER PRIMARY KEY, farm_id INTEGER NOT NULL REFERENCES farms(id), crop TEXT NOT NULL, start_date TEXT NOT NULL,
 end_date TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), CHECK(start_date <= end_date)
);
CREATE TABLE IF NOT EXISTS vehicles (
 id INTEGER PRIMARY KEY, number TEXT NOT NULL UNIQUE, name TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1))
);
CREATE TABLE IF NOT EXISTS availability (
 user_id INTEGER NOT NULL REFERENCES users(id), date TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('AVAILABLE','MAYBE','UNAVAILABLE')),
 PRIMARY KEY(user_id,date)
);
CREATE TABLE IF NOT EXISTS shifts (
 id INTEGER PRIMARY KEY, date TEXT NOT NULL, slot TEXT NOT NULL CHECK(slot IN ('MORNING','EVENING')),
 season_id INTEGER NOT NULL REFERENCES seasons(id), leader_id INTEGER NOT NULL REFERENCES users(id), goal REAL NOT NULL CHECK(goal >= 0),
 notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PUBLISHED','COMPLETED','CANCELLED')),
 created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS shift_pickers (shift_id INTEGER NOT NULL REFERENCES shifts(id), user_id INTEGER NOT NULL REFERENCES users(id), PRIMARY KEY(shift_id,user_id));
CREATE TABLE IF NOT EXISTS shift_vehicles (shift_id INTEGER NOT NULL REFERENCES shifts(id), vehicle_id INTEGER NOT NULL REFERENCES vehicles(id), PRIMARY KEY(shift_id,vehicle_id));
CREATE TABLE IF NOT EXISTS quantities (
 shift_id INTEGER NOT NULL REFERENCES shifts(id), user_id INTEGER NOT NULL REFERENCES users(id), quantity REAL NOT NULL CHECK(quantity >= 0),
 updated_by INTEGER NOT NULL REFERENCES users(id), updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(shift_id,user_id)
);
CREATE TABLE IF NOT EXISTS notifications (
 id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_events (
 id INTEGER PRIMARY KEY, actor_id INTEGER NOT NULL REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL,
 entity_id INTEGER NOT NULL, metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sessions_hash ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_shift_slot ON shifts(date,slot);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,created_at);
