ALTER TABLE users ADD COLUMN bank_account_holder TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bank_number TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bank_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bank_branch_number TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bank_branch_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bank_account_number TEXT NOT NULL DEFAULT '';
