-- הוצאות: שורה לכל חשבונית/קבלה, עם קובץ מקור אופציונלי שנשמר בשרת

CREATE TABLE expenses (
 id INTEGER PRIMARY KEY,
 source TEXT NOT NULL CHECK(source IN ('MANUAL','CAMERA','UPLOAD')),
 invoice_date TEXT CHECK(invoice_date IS NULL OR invoice_date GLOB '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'),
 business_type TEXT,
 business_department TEXT,
 secondary_category TEXT,
 execution_area TEXT,
 trip TEXT,
 supplier_name TEXT,
 invoice_number TEXT,
 details TEXT,
 transaction_currency TEXT,
 exchange_rate REAL,
 amount_transaction_currency REAL,
 amount_before_vat REAL,
 vat REAL,
 total_ils REAL,
 payment_currency TEXT,
 payment_date TEXT,
 paying_account TEXT,
 payment_method TEXT,
 invoice_type TEXT,
 tax_classification TEXT,
 expense_type TEXT,
 personal_area TEXT,
 statement_line_date TEXT,
 has_local_file TEXT,
 report_folder TEXT,
 in_ledger TEXT,
 ledger_line TEXT,
 tax_year INTEGER,
 handling_status TEXT,
 extra_details TEXT,
 processing_date TEXT,
 new_file_name TEXT,
 file_link TEXT,
 review_notes TEXT,
 file_path TEXT,
 file_mime TEXT,
 created_by INTEGER NOT NULL REFERENCES users(id),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX expenses_invoice_date ON expenses(invoice_date);
