// Regenerates src/lib/israeli-banks-data.ts from Bank of Israel's "branches for clearing" dataset on data.gov.il.
// Run: npx tsx scripts/update-israeli-banks.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const RESOURCE_ID = "b3f7616d-1c65-497d-afd5-d5ba972bfc1d"; // סניפים לסליקה – עברית
const API = `https://data.gov.il/api/3/action/datastore_search?resource_id=${RESOURCE_ID}&limit=10000`;
// Credit-card companies, clearing houses and Bank of Israel itself — not places a worker holds a salary account.
const EXCLUDED_BANKS = new Set([1, 6, 50, 59, 99]);

type Row = { id: number; name: string; branch_code: number; branch_name: string; city: string | null; close_date: string | null };

async function main() {
  const res = await fetch(API, { headers: { "User-Agent": "Mozilla/5.0" } });
  if (!res.ok) throw new Error(`data.gov.il responded ${res.status}`);
  const rows = ((await res.json()) as { result: { records: Row[] } }).result.records;

  const clean = (s: string | null) => (s ?? "").replace(/\s+/g, " ").trim();
  const banks = new Map<number, { name: string; branches: Map<number, [number, string, string]> }>();
  for (const r of rows) {
    if (EXCLUDED_BANKS.has(r.id) || clean(r.close_date)) continue;
    const bank = banks.get(r.id) ?? { name: clean(r.name).replace(/\s*בע"מ$/, ""), branches: new Map() };
    bank.branches.set(r.branch_code, [r.branch_code, clean(r.branch_name), clean(r.city)]);
    banks.set(r.id, bank);
  }

  const data = [...banks.entries()]
    .sort(([a], [b]) => a - b)
    .map(([code, b]) => ({ code, name: b.name, branches: [...b.branches.values()].sort((x, y) => x[0] - y[0]) }));

  const out = `// Generated by scripts/update-israeli-banks.ts on ${new Date().toISOString().slice(0, 10)} — do not edit by hand.
// Source: Bank of Israel, "סניפים לסליקה" (data.gov.il resource ${RESOURCE_ID}).
// Branch tuple: [branch number, branch name, city].
export const ISRAELI_BANKS: ReadonlyArray<{ code: number; name: string; branches: ReadonlyArray<readonly [number, string, string]> }> = ${JSON.stringify(data)};
`;
  writeFileSync(join(__dirname, "../src/lib/israeli-banks-data.ts"), out);
  console.log(`Wrote ${data.length} banks, ${data.reduce((n, b) => n + b.branches.length, 0)} branches`);
}

main().catch(error => { console.error(error); process.exit(1); });
